name: validate packer
#workflow will run after the pull request is raised
on:
  pull_request:
    branches:
    - main
jobs:
  packer_build:
#this ami packer file will run on ubuntu latest and will create the AMI
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      
    steps:
    - uses: actions/checkout@v3
    - name: Python dependencies installed
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
#the workflow will validate and build the ami through the below code
    - name: Format Packer Template
      run: |

        # Run packer fmt and capture the exit code
        packer fmt -check .

        # Check the exit code and fail the workflow if changes were made
        if [ $? -ne 0 ]; then
        echo "Packer template formatting check failed. Please run 'packer fmt' locally and commit the changes."
        exit 1
        fi

    - name: Validate Packer Template
      run: |
        # Run packer validate and capture the exit code
        packer validate -syntax-only .

        # Check the exit code and fail the workflow if validation fails
        if [ $? -ne 0 ]; then
          echo "Packer template validation failed. Please ensure the template is correct before merging the pull request."
          exit 1
        fi